# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\AhJayzZ\Desktop\NTUST Assignment\Project\Smart-Learning-System\project_codes\image_recognition\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SmartLearningSystemGUI(object):
    def setupUi(self, SmartLearningSystemGUI):
        SmartLearningSystemGUI.setObjectName("SmartLearningSystemGUI")
        SmartLearningSystemGUI.resize(1115, 716)
        self.result_label = QtWidgets.QLabel(SmartLearningSystemGUI)
        self.result_label.setGeometry(QtCore.QRect(750, 0, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.result_label.setFont(font)
        self.result_label.setObjectName("result_label")
        self.warning_label = QtWidgets.QLabel(SmartLearningSystemGUI)
        self.warning_label.setGeometry(QtCore.QRect(220, 640, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.warning_label.setFont(font)
        self.warning_label.setAutoFillBackground(False)
        self.warning_label.setObjectName("warning_label")
        self.confirm_btn = QtWidgets.QPushButton(SmartLearningSystemGUI)
        self.confirm_btn.setGeometry(QtCore.QRect(760, 640, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.confirm_btn.setFont(font)
        self.confirm_btn.setObjectName("confirm_btn")
        self.revise_btn = QtWidgets.QPushButton(SmartLearningSystemGUI)
        self.revise_btn.setGeometry(QtCore.QRect(1030, 590, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.revise_btn.setFont(font)
        self.revise_btn.setObjectName("revise_btn")
        self.tableWidget = QtWidgets.QTableWidget(SmartLearningSystemGUI)
        self.tableWidget.setGeometry(QtCore.QRect(0, 10, 741, 631))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.camera_label = QtWidgets.QLabel(SmartLearningSystemGUI)
        self.camera_label.setGeometry(QtCore.QRect(0, 10, 741, 631))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.camera_label.setFont(font)
        self.camera_label.setScaledContents(False)
        self.camera_label.setAlignment(QtCore.Qt.AlignCenter)
        self.camera_label.setObjectName("camera_label")
        self.result_list = QtWidgets.QListWidget(SmartLearningSystemGUI)
        self.result_list.setGeometry(QtCore.QRect(760, 40, 351, 541))
        self.result_list.setObjectName("result_list")
        self.revise_textbox = QtWidgets.QLineEdit(SmartLearningSystemGUI)
        self.revise_textbox.setGeometry(QtCore.QRect(760, 590, 261, 41))
        self.revise_textbox.setObjectName("revise_textbox")

        self.retranslateUi(SmartLearningSystemGUI)
        QtCore.QMetaObject.connectSlotsByName(SmartLearningSystemGUI)

    def retranslateUi(self, SmartLearningSystemGUI):
        _translate = QtCore.QCoreApplication.translate
        SmartLearningSystemGUI.setWindowTitle(_translate("SmartLearningSystemGUI", "Dialog"))
        self.result_label.setText(_translate("SmartLearningSystemGUI", "辨識結果:"))
        self.warning_label.setText(_translate("SmartLearningSystemGUI", "Warning:光線不足"))
        self.confirm_btn.setText(_translate("SmartLearningSystemGUI", "新增單字至資料庫"))
        self.revise_btn.setText(_translate("SmartLearningSystemGUI", "修正"))
        self.camera_label.setText(_translate("SmartLearningSystemGUI", "ThisLabelWillBeChangedToVideoFrame"))
